name: Save Output Folder to Another Repo

on:
  push:
    branches:
      - main

jobs:
  save_output:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo-A
        uses: actions/checkout@v3

      - name: Generate an output folder with files
        run: |
          mkdir -p output_folder
          echo "Generated at $(date)" > output_folder/output.txt
          echo "Additional log file" > output_folder/log.txt

      - name: Push output folder to Repo-B
        env:
          REPO_B_PAT: ${{ secrets.REPO_B_PAT }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Clone Repo-B using the PAT token
          git clone https://x-access-token:${REPO_B_PAT}@github.com/niharika17032001/Repo-B.git

          # Move into Repo-B directory
          cd Repo-B

          # Copy the output folder from Repo-A to Repo-B
          cp -r ../output_folder .

          # Commit and push changes
          git add output_folder
          git commit -m "Updated output folder from Repo-A"
          git push origin main
